export const FROM_CONFIG = [
	{
		id: 1,
		name: 'address1',
		type: 'text',
		label: 'Address 1',
		isEditable: true,
		isRequired: true,
		value: 'address1',
	},
	{
		id: 2,
		name: 'address2',
		type: 'text',
		label: 'Address 2',
		isEditable: true,
		isRequired: false,
		value: 'address2',
	},
	{
		id: 3,
		name: 'district',
		type: 'text',
		label: 'District',
		isEditable: true,
		isRequired: false,
		value: 'district',
	},
	{
		id: 4,
		name: 'city',
		type: 'text',
		label: 'City',
		isEditable: true,
		isRequired: true,
		value: 'city',
	},
	{
		id: 5,
		name: 'state',
		type: 'text',
		label: 'State',
		isEditable: true,
		isRequired: true,
		value: 'state',
	},
	{
		id: 6,
		name: 'country',
		type: 'text',
		label: 'Country',
		isEditable: true,
		isRequired: true,
		value: 'country',
	},
	{
		id: 7,
		name: 'postal_code',
		type: 'text',
		label: 'Pin code',
		isEditable: true,
		isRequired: true,
		value: 'postal_code',
	},
];
