export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNUP = 'USER_SIGNUP';
export const UPDATE_IS_CART_EMPTY = 'UPDATE_IS_CART_EMPTY';
export const SET_USER_DATA_LOADING = 'SET_USER_DATA_LOADING';
