export const INIT_WISHLIST = 'INIT_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const EMPTY_WISHLIST = 'EMPTY_WISHLIST';
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';
export const RESET_WISHLIST_STATE = 'RESET_WISHLIST_STATE';
